# Generated by Django 3.2.19 on 2023-08-10 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('hostip', models.CharField(max_length=50, verbose_name='主机IP')),
                ('port', models.CharField(max_length=50, verbose_name='端口号')),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='MysqlInstallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='类型,1代表普通，0代表特权用户')),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=50, verbose_name='密码')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usertype', verbose_name='类型,1代表普通，0代表特权用户')),
            ],
            options={
                'db_table': 'user_auth',
            },
        ),
    ]
