# Generated by Django 3.2.19 on 2023-08-14 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('hostip', models.CharField(max_length=50, verbose_name='主机IP')),
                ('port', models.CharField(max_length=50, verbose_name='端口号')),
            ],
            options={
                'db_table': 'assets',
            },
        ),
        migrations.CreateModel(
            name='MysqlInstallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_id', models.CharField(max_length=50, verbose_name='执行id')),
                ('h_ip', models.CharField(max_length=50, verbose_name='执行主机IP')),
                ('h_user', models.CharField(max_length=50, verbose_name='执行用户')),
                ('h_type', models.CharField(max_length=50, verbose_name='类型')),
                ('h_d_url', models.CharField(max_length=50, verbose_name='版本')),
                ('h_s_url', models.CharField(max_length=50, verbose_name='脚本')),
                ('h_status', models.CharField(max_length=50, verbose_name='状态')),
            ],
            options={
                'db_table': 'mysql_install_history',
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='类型,1代表普通，0代表特权用户')),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=50, verbose_name='密码')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usertype', verbose_name='类型,1代表普通，0代表特权用户')),
            ],
            options={
                'db_table': 'user_auth',
            },
        ),
    ]
