# Generated by Django 3.2.19 on 2023-08-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('ipadders', models.CharField(max_length=50, verbose_name='ip地址')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=50, verbose_name='密码')),
                ('port', models.CharField(max_length=50, verbose_name='端口号')),
                ('type', models.CharField(max_length=50, verbose_name='类型')),
            ],
            options={
                'db_table': 'user_auth',
            },
        ),
    ]
