# Generated by Django 3.2.19 on 2023-08-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliyunAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionId', models.CharField(max_length=50, verbose_name='区域地方')),
                ('instanceIds', models.CharField(max_length=50, verbose_name='实例id')),
                ('dataSnapshotId', models.CharField(max_length=50, verbose_name='数据盘快照id')),
                ('instanceName', models.CharField(max_length=50, verbose_name='实例名称')),
                ('instanceType', models.CharField(max_length=50, verbose_name='实例类型')),
                ('instanceChargeType', models.CharField(max_length=50, verbose_name='付费模式')),
                ('keyPairName', models.CharField(max_length=50, verbose_name='密钥名称')),
                ('securityGroupId', models.CharField(max_length=50, verbose_name='安全组id')),
                ('vSwitchId', models.CharField(max_length=50, verbose_name='虚拟交换机')),
            ],
            options={
                'db_table': 'aliyun_assets',
            },
        ),
    ]
