# Generated by Django 3.2.19 on 2023-08-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aliyunassets'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliyunEcsAssets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regionId', models.CharField(max_length=50, verbose_name='实例区域id')),
                ('instanceId', models.CharField(max_length=50, verbose_name='实例id')),
                ('instanceName', models.CharField(max_length=50, verbose_name='实例名称')),
                ('memory', models.CharField(max_length=50, verbose_name='内存')),
                ('instanceChargeType', models.CharField(max_length=50, verbose_name='付费类型')),
                ('cpu', models.CharField(max_length=50, verbose_name='cpu')),
                ('osName', models.CharField(max_length=50, verbose_name='系统名称')),
                ('expiredTime', models.CharField(max_length=50, verbose_name='到期时间')),
                ('imageId', models.CharField(max_length=50, verbose_name='镜像id')),
                ('status', models.CharField(max_length=50, verbose_name='实例状态')),
                ('startTime', models.CharField(max_length=50, verbose_name='开始时间')),
                ('privateIpAddress', models.CharField(max_length=50, verbose_name='私有IP')),
                ('vpcId', models.CharField(max_length=50, verbose_name='vpc Id')),
                ('vswitchId', models.CharField(max_length=50, verbose_name='虚拟网卡')),
                ('instanceType', models.CharField(max_length=50, verbose_name='实例类型')),
                ('keyPairName', models.CharField(max_length=50, verbose_name='密钥对')),
                ('zoneId', models.CharField(max_length=50, verbose_name='地区id')),
                ('tags', models.CharField(max_length=500, verbose_name='标签')),
                ('securityGroupIds', models.CharField(max_length=50, verbose_name='安全组id')),
            ],
            options={
                'db_table': 'aliyun_ecs_assets',
            },
        ),
        migrations.AlterField(
            model_name='aliyunassets',
            name='regionId',
            field=models.CharField(max_length=50, verbose_name='实例区域'),
        ),
    ]
