# Generated by Django 3.2.19 on 2023-08-22 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230822_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliyunecsassets',
            name='securityGroupIds',
            field=models.CharField(max_length=500, verbose_name='安全组id'),
        ),
    ]
