# Generated by Django 3.2.19 on 2023-08-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_aliyundescriberegions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AliyunDescribeVpcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cenStatus', models.CharField(max_length=50, verbose_name='vpc状态')),
                ('cidrBlock', models.CharField(max_length=50, verbose_name='vpc网段')),
                ('regionId', models.CharField(max_length=50, verbose_name='实力区域id')),
                ('resourceGroupId', models.CharField(max_length=50, verbose_name='资源组id')),
                ('tags', models.CharField(max_length=50, verbose_name='标签')),
                ('vSwitchIds', models.CharField(max_length=50, verbose_name='虚拟交换机')),
                ('vpcId', models.CharField(max_length=50, verbose_name='vpc id')),
                ('vpcName', models.CharField(max_length=50, verbose_name='vpc名称')),
                ('creationTime', models.CharField(max_length=50, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'aliyun_describe_vpcs',
            },
        ),
    ]
