# Generated by Django 3.2.19 on 2023-08-24 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_aliyundescribevpcs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliyundescribevpcs',
            name='tags',
            field=models.CharField(max_length=500, verbose_name='标签'),
        ),
    ]
