# Generated by Django 3.2.19 on 2023-08-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_aliyundescribevpcs_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliyunecsassets',
            name='description',
            field=models.CharField(default='slave', max_length=50, verbose_name='描述'),
        ),
    ]
